/* Generated By:JJTree: Do not edit this line. ASTISSTR.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTISSTR extends SimpleNode {
  public ASTISSTR(int id) {
    super(id);
  }

  public ASTISSTR(HL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HLVisitor visitor, Object data) throws Exception {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3170f0c4e36ddf9d42d29a363573cee4 (do not edit this line) */
