/* Generated By:JJTree: Do not edit this line. ASTif_stat.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTif_stat extends SimpleNode {
  public ASTif_stat(int id) {
    super(id);
  }

  public ASTif_stat(HL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HLVisitor visitor, Object data) throws Exception {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1c7934b3b8ec9585c9dae3b11977ea42 (do not edit this line) */
