/* Generated By:JJTree: Do not edit this line. ASTISLST.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTISLST extends SimpleNode {
  public ASTISLST(int id) {
    super(id);
  }

  public ASTISLST(HL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HLVisitor visitor, Object data) throws Exception {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6b5fd94aaaa69c1a275e014837ba3211 (do not edit this line) */
