/* Generated By:JJTree: Do not edit this line. ASTparam_decls.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTparam_decls extends SimpleNode {
  public ASTparam_decls(int id) {
    super(id);
  }

  public ASTparam_decls(HL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HLVisitor visitor, Object data) throws Exception {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d835287cb58fa9b006528a6eeaafd0c2 (do not edit this line) */
