/* Generated By:JJTree: Do not edit this line. ASTSTR.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSTR extends SimpleNode {
  public ASTSTR(int id) {
    super(id);
  }

  public ASTSTR(HL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HLVisitor visitor, Object data) throws Exception {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4e3cf5e1597d30aef3b2fc8b5aad76d6 (do not edit this line) */
