/* Generated By:JavaCC: Do not edit this line. HLTreeConstants.java Version 5.0 */
public interface HLTreeConstants
{
  public int JJTVOID = 0;
  public int JJTBODY = 1;
  public int JJTCLAUSE = 2;
  public int JJTANY = 3;
  public int JJTINT = 4;
  public int JJTSTR = 5;
  public int JJTLST = 6;
  public int JJTSIMPLE_DECL = 7;
  public int JJTFN_DECL = 8;
  public int JJTPARAM_DECLS = 9;
  public int JJTPARAM_DECL = 10;
  public int JJTIF_STAT = 11;
  public int JJTNULL = 12;
  public int JJTFOR_STAT = 13;
  public int JJTWHILE_STAT = 14;
  public int JJTASSIGNMENT = 15;
  public int JJTFN_CALL = 16;
  public int JJTPARAMETERS = 17;
  public int JJTPRINT_STAT = 18;
  public int JJTPRINTLN_STAT = 19;
  public int JJTRETURN_STAT = 20;
  public int JJTOR = 21;
  public int JJTAND = 22;
  public int JJTNOT = 23;
  public int JJTISINT = 24;
  public int JJTISSTR = 25;
  public int JJTISLST = 26;
  public int JJTCOMPARISON = 27;
  public int JJTLT = 28;
  public int JJTLE = 29;
  public int JJTGT = 30;
  public int JJTGE = 31;
  public int JJTEQ = 32;
  public int JJTNE = 33;
  public int JJTIN = 34;
  public int JJTSUM = 35;
  public int JJTNEG = 36;
  public int JJTPOS = 37;
  public int JJTMUL = 38;
  public int JJTDIV = 39;
  public int JJTMOD = 40;
  public int JJTINDEX = 41;
  public int JJTLIST = 42;
  public int JJTIDENTIFIER = 43;
  public int JJTINTEGER = 44;
  public int JJTSTRING = 45;


  public String[] jjtNodeName = {
    "void",
    "body",
    "clause",
    "ANY",
    "INT",
    "STR",
    "LST",
    "simple_decl",
    "fn_decl",
    "param_decls",
    "param_decl",
    "if_stat",
    "NULL",
    "for_stat",
    "while_stat",
    "assignment",
    "fn_call",
    "parameters",
    "print_stat",
    "println_stat",
    "return_stat",
    "or",
    "and",
    "not",
    "ISINT",
    "ISSTR",
    "ISLST",
    "comparison",
    "LT",
    "LE",
    "GT",
    "GE",
    "EQ",
    "NE",
    "IN",
    "sum",
    "neg",
    "pos",
    "mul",
    "div",
    "mod",
    "index",
    "list",
    "identifier",
    "integer",
    "string",
  };
}
/* JavaCC - OriginalChecksum=2c26a3351faeedc34b63f63aa1a92989 (do not edit this line) */
