/* Generated By:JavaCC: Do not edit this line. HLVisitor.java Version 5.0 */
public interface HLVisitor
{
  public Object visit(SimpleNode node, Object data) throws Exception;
  public Object visit(ASTbody node, Object data) throws Exception;
  public Object visit(ASTclause node, Object data) throws Exception;
  public Object visit(ASTANY node, Object data) throws Exception;
  public Object visit(ASTINT node, Object data) throws Exception;
  public Object visit(ASTSTR node, Object data) throws Exception;
  public Object visit(ASTLST node, Object data) throws Exception;
  public Object visit(ASTsimple_decl node, Object data) throws Exception;
  public Object visit(ASTfn_decl node, Object data) throws Exception;
  public Object visit(ASTparam_decls node, Object data) throws Exception;
  public Object visit(ASTparam_decl node, Object data) throws Exception;
  public Object visit(ASTif_stat node, Object data) throws Exception;
  public Object visit(ASTNULL node, Object data) throws Exception;
  public Object visit(ASTfor_stat node, Object data) throws Exception;
  public Object visit(ASTwhile_stat node, Object data) throws Exception;
  public Object visit(ASTassignment node, Object data) throws Exception;
  public Object visit(ASTfn_call node, Object data) throws Exception;
  public Object visit(ASTparameters node, Object data) throws Exception;
  public Object visit(ASTprint_stat node, Object data) throws Exception;
  public Object visit(ASTprintln_stat node, Object data) throws Exception;
  public Object visit(ASTreturn_stat node, Object data) throws Exception;
  public Object visit(ASTor node, Object data) throws Exception;
  public Object visit(ASTand node, Object data) throws Exception;
  public Object visit(ASTnot node, Object data) throws Exception;
  public Object visit(ASTISINT node, Object data) throws Exception;
  public Object visit(ASTISSTR node, Object data) throws Exception;
  public Object visit(ASTISLST node, Object data) throws Exception;
  public Object visit(ASTcomparison node, Object data) throws Exception;
  public Object visit(ASTLT node, Object data) throws Exception;
  public Object visit(ASTLE node, Object data) throws Exception;
  public Object visit(ASTGT node, Object data) throws Exception;
  public Object visit(ASTGE node, Object data) throws Exception;
  public Object visit(ASTEQ node, Object data) throws Exception;
  public Object visit(ASTNE node, Object data) throws Exception;
  public Object visit(ASTIN node, Object data) throws Exception;
  public Object visit(ASTsum node, Object data) throws Exception;
  public Object visit(ASTneg node, Object data) throws Exception;
  public Object visit(ASTpos node, Object data) throws Exception;
  public Object visit(ASTmul node, Object data) throws Exception;
  public Object visit(ASTdiv node, Object data) throws Exception;
  public Object visit(ASTmod node, Object data) throws Exception;
  public Object visit(ASTindex node, Object data) throws Exception;
  public Object visit(ASTlist node, Object data) throws Exception;
  public Object visit(ASTidentifier node, Object data) throws Exception;
  public Object visit(ASTinteger node, Object data) throws Exception;
  public Object visit(ASTstring node, Object data) throws Exception;
}
/* JavaCC - OriginalChecksum=70f5396faf2697e3b3c8ef2a8256f32c (do not edit this line) */
